export const environment = {
  production: true,
  apiBaseUrl: '/api',
  chatlogApiUrl: '/api/chatlog',
  chatTurnsApiUrl: '/api/chatlog/turns',
  chatlogDownloadApiUrl: '/api/chatlog/download',
  messagesApiUrl: '/api/messages',
  editorBlocksApiUrl: '/api/editor/blocks',
  optionsApiUrl: '/api/options',
  flowStatesApiUrl: '/api/flow/states',
  handoffSessionsApiUrl: '/api/handoff/sessions',
  agentSendApiUrl: '/api/agent/send',
  botSendApiUrl: '/api/bot/send',
  resumeApiUrl: '/api/resume',
};
